//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apointement
    {
        public int apointmentId { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string managerId { get; set; }
        public string tenentId { get; set; }
    
        public virtual manager manager { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
