//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appartement
    {
        public int appartementNo { get; set; }
        public string buildingNo { get; set; }
        public string statusId { get; set; }
        public int roomNo { get; set; }
        public int washroomNo { get; set; }
        public int floorNo { get; set; }
        public string tenantId { get; set; }
    
        public virtual status status { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
