//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class building
    {
        public string buildingNo { get; set; }
        public string streetName { get; set; }
        public string postalCode { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string ownerId { get; set; }
        public string managerId { get; set; }
    
        public virtual manager manager { get; set; }
        public virtual owner owner { get; set; }
    }
}
